In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
netflix_dataset=pd.read_csv('/content/drive/MyDrive/NETFLIX/Copy of combined_data_1.txt.zip',header=None,names=['customer_id','ratings'],usecols=[0,1])

In [ ]:
netflix_dataset

         customer_id  ratings
0                 1:      NaN
1            1488844      3.0
2             822109      5.0
3             885013      4.0
4              30878      4.0
...              ...      ...
24058258     2591364      2.0
24058259     1791000      2.0
24058260      512536      5.0
24058261      988963      3.0
24058262     1704416      3.0

[24058263 rows x 2 columns]

# CUSTOMER ID COLUMN CONSIST OF BOTH MOVIE ID AND CUSTOMER ID,WHICH IS REPRESENTED AS NAN AT RATINGS COLUMN.

In [ ]:
# NUMBER OF MOVIES:
movie_count=netflix_dataset.isnull().sum()
movie_count=movie_count['ratings']
movie_count

4499

In [ ]:
# FINDING OF TOTAL NUMBER OF CUSTOMERS:-
total_customer=netflix_dataset['customer_id'].nunique() - movie_count

In [ ]:
total_customer #TOTAL NUMBER OF CUSTOMERS

470758

In [ ]:
# COUNT OF RATINGS:-
rating_count=netflix_dataset['ratings'].count() - movie_count

In [ ]:
rating_count

24049265

In [ ]:
given_ratings=netflix_dataset['ratings'].value_counts() #unique count of ratings

In [ ]:
# NOW WE HAVE TO REMOVE THE NUMBER OF MOVIE ID FROM CUSTOMER ID COL,AND NEED TO SEPERATE THEM.
customer_ids=[]
for value in netflix_dataset['customer_id']:
  if ':' in value:
    id=value.replace(':','')
  customer_ids.append(id)

In [ ]:
customer_ids

['1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 ...]

In [ ]:
netflix_dataset['movie_id']=customer_ids #ADDING THE ARRAY WITH THE DATASET.

In [ ]:
netflix_dataset

         customer_id  ratings movie_id
0                 1:      NaN        1
1            1488844      3.0        1
2             822109      5.0        1
3             885013      4.0        1
4              30878      4.0        1
...              ...      ...      ...
24058258     2591364      2.0     4499
24058259     1791000      2.0     4499
24058260      512536      5.0     4499
24058261      988963      3.0     4499
24058262     1704416      3.0     4499

[24058263 rows x 3 columns]

In [ ]:
# now removing the cust_id from custimer_if column.
netflix_dataset.dropna(inplace=True)

In [ ]:
netflix_dataset

         customer_id  ratings movie_id
1            1488844      3.0        1
2             822109      5.0        1
3             885013      4.0        1
4              30878      4.0        1
5             823519      3.0        1
...              ...      ...      ...
24058258     2591364      2.0     4499
24058259     1791000      2.0     4499
24058260      512536      5.0     4499
24058261      988963      3.0     4499
24058262     1704416      3.0     4499

[24053764 rows x 3 columns]

In [ ]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   customer_id  object
 1   ratings      float64
 2   movie_id     object
dtypes: float64(1), object(2)
memory usage: 734.1+ MB

In [ ]:
# CONVERTING THE CUSTOMER_ID INTO INT
netflix_dataset['customer_id']=netflix_dataset['customer_id'].astype(int)

In [ ]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   customer_id  int64
 1   ratings      float64
 2   movie_id     object
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [ ]:
movie_rate_count=netflix_dataset['movie_id'].value_counts()

In [ ]:
movie_rate_count # these are the unique no. of ratings a movie got.

movie_id
1905    193941
2152    162597
3860    160454
4432    156183
571     154832
         ...
4294        44
915         43
3656        42
4338        39
4362        36
Name: count, Length: 4499, dtype: int64

In [ ]:
# we need movies above 60% rating threshold.
threshold=round(movie_rate_count.quantile(0.6))
threshold

908

In [ ]:
dropped_movies=movie_rate_count[movie_rate_count < threshold].index #these are the movies which are less than threshold review.
dropped_movies

Index(['1598', '1733', '1647', '4099', '1616', '1446', '263', '4259', '160',
       '1988',
       ...
       '1858', '4035', '3693', '2805', '820', '4294', '915', '3656', '4338',
       '4362'],
      dtype='object', name='movie_id', length=2699)

In [ ]:
# if we find the number of customers then we can find that how many ratings each people has done.
customer_review_count=netflix_dataset['customer_id'].value_counts()
customer_review_count

customer_id
305344     4467
387418     4422
2439493    4195
1664010    4019
2118461    3769
           ...
1300341       1
2550360       1
11848         1
930788        1
594210        1
Name: count, Length: 470758, dtype: int64

In [ ]:
# Benchmark for the customer reviw:-
bench_mark=customer_review_count.quantile(0.6)
bench_mark

36.0

In [ ]:
# dropped customers:
dropped_customer=customer_review_count[customer_review_count < bench_mark].index
dropped_customer

Index([2194851,  600295, 1739398, 1157368,  532108, 2157249,  256134,  640441,
       1272324, 1346990,
       ...
       1969065,  899932,  611596, 2147176,  811650, 1300341, 2550360,   11848,
        930788,  594210],
      dtype='int64', name='customer_id', length=282042)

In [ ]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   customer_id  int64
 1   ratings      float64
 2   movie_id     object
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [ ]:
# now we need these customers and movies which are not in dropped.using isin() method we will perform.
netflix_dataset=netflix_dataset[~netflix_dataset['customer_id'].isin(dropped_customer)]
netflix_dataset=netflix_dataset[~netflix_dataset['movie_id'].isin(dropped_movies)]

In [ ]:
netflix_dataset

          customer_id  ratings movie_id
696            712664      5.0        3
697           1331154      4.0        3
698           2632461      3.0        3
699             44937      5.0        3
700            656399      4.0        3
...               ...      ...      ...
24056842      1055714      5.0     4496
24056843      2643029      4.0     4496
24056844       267802      4.0     4496
24056845      1559566      3.0     4496
24056846       293198      3.0     4496

[19695836 rows x 3 columns]

#**MODEL BUILDING PART:-**

In [ ]:
#LOAD THE SECOND DATASET:-
df_title=pd.read_csv('/content/drive/MyDrive/NETFLIX/Copy of movie_titles.csv',encoding='ISO-8859-1',header=None,names=['movie_id','year','name'],usecols=[0,1,2])

In [ ]:
df_title

       movie_id    year                                               name
0             1  2003.0                                    Dinosaur Planet
1             2  2004.0                         Isle of Man TT 2004 Review
2             3  1997.0                                          Character
3             4  1994.0                       Paula Abdul's Get Up & Dance
4             5  2004.0                           The Rise and Fall of ECW
...         ...     ...                                                ...
17764     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765     17767  2004.0                  Fidel Castro: American Experience
17766     17768  2000.0                                              Epoch
17767     17769  2003.0                                        The Company
17768     17770  2003.0                                       Alien Hunter

[17769 rows x 3 columns]

In [ ]:
!pip install numpy==1.26.4
!pip install scikit-surprise==1.1.4

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)
Collecting scikit-surprise==1.1.4
  Using cached scikit_surprise-1.1.4.tar.gz (154 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise==1.1.4) (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise==1.1.4) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise==1.1.4) (1.16.3)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp312-cp312-linux_x86_64.whl size=2554972 sha256=a74582cbcff0511e969c6e9511f42dfcb1434326f0a56096354c6153b56a6f2a
  Stored in directory: /root/.cache/pip/wheels/75/fa/bc/739bc2cb1fbaab6061854e6cfbb81a0ae52c92a502a7fa454b
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.4

In [ ]:
# Import the necessary libraries from surprise
from surprise import SVD, Reader, Dataset
from surprise.model_selection import cross_validate

In [ ]:
reader=Reader() #its for reading the objects

In [ ]:
data=Dataset.load_from_df(netflix_dataset[['movie_id','customer_id','ratings']][:1000000],reader)

In [ ]:
data #data is stored into the object

In [ ]:
model=SVD()

In [ ]:
#cross validation technique using rmse(root mean square error)
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([0.96572158, 0.96763369, 0.96631559]),
 'fit_time': (21.79057240486145, 17.110886573791504, 16.41115093231201),
 'test_time': (3.6133830547332764, 3.1106319427490234, 4.527519226074219)}

In [ ]:
user_rating=netflix_dataset[netflix_dataset['customer_id']==1331154]

In [ ]:
user_rating

          customer_id  ratings movie_id
697           1331154      4.0        3
5178          1331154      4.0        8
31460         1331154      3.0       18
92840         1331154      4.0       30
224761        1331154      3.0       44
...               ...      ...      ...
23439584      1331154      4.0     4389
23546489      1331154      2.0     4402
23649431      1331154      4.0     4432
23844441      1331154      3.0     4472
23985561      1331154      4.0     4488

[253 rows x 3 columns]

In [ ]:
movie_title=df_title.copy() #total movies

In [ ]:
movie_title

       movie_id    year                                               name
0             1  2003.0                                    Dinosaur Planet
1             2  2004.0                         Isle of Man TT 2004 Review
2             3  1997.0                                          Character
3             4  1994.0                       Paula Abdul's Get Up & Dance
4             5  2004.0                           The Rise and Fall of ECW
...         ...     ...                                                ...
17764     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765     17767  2004.0                  Fidel Castro: American Experience
17766     17768  2000.0                                              Epoch
17767     17769  2003.0                                        The Company
17768     17770  2003.0                                       Alien Hunter

[17769 rows x 3 columns]

In [ ]:
# i want to eliminate dropped_movies columns from the movie title column

# Now, eliminate the movies present in 'dropped_movies' from 'movie_title' DataFrame
movie_title = movie_title[~movie_title['movie_id'].astype(str).isin(dropped_movies.astype(str))]
movie_title

       movie_id    year                                               name
2             3  1997.0                                          Character
4             5  2004.0                           The Rise and Fall of ECW
5             6  1997.0                                               Sick
7             8  2004.0                         What the #$*! Do We Know!?
15           16  1996.0                                          Screamers
...         ...     ...                                                ...
17764     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765     17767  2004.0                  Fidel Castro: American Experience
17766     17768  2000.0                                              Epoch
17767     17769  2003.0                                        The Company
17768     17770  2003.0                                       Alien Hunter

[15070 rows x 3 columns]

In [ ]:
movie_title['Estimated']=movie_title['movie_id'].apply(lambda x: model.predict(1331154,x).est)

/tmp/ipython-input-2318960625.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_title['Estimated']=movie_title['movie_id'].apply(lambda x: model.predict(1331154,x).est)

In [ ]:
#using for loop we can do this also
#est=[]
#for i in movie_title['movie_id']:
 # est.append(model.predict(1331154,i).est)
#movie_title['Estimated']=est

In [ ]:
movie_title.sort_values(by='Estimated',ascending=False).head(10) # this the prediction the customer can rate these movies

,movie_id,year,name,Estimated
3997,3998,1988.0,Joseph Campbell and The Power of Myth,4.515594
8813,8815,1992.0,Chaplin: The Movie,4.454236
10899,10901,2004.0,The Keeper of Time,4.449699
17449,17451,2000.0,Along for the Ride,4.383439
11041,11043,1970.0,Mary Tyler Moore: Season 1,4.321351
9397,9399,1991.0,Legend of the Dragon Kings: White Dragon,4.302429
6542,6544,1993.0,French & Saunders: At the Movies,4.290577
4678,4679,1965.0,Battle of the Bulge,4.249003
6734,6736,2005.0,Robots,4.206617
12629,12631,2002.0,The Ultimate Beginner Series: Rock Guitar Styles,4.201169

## This is how by changing the custimer id we can predict the rating the customer can provide for all the movies and based on this movies can be suggested.

# Model Deployment:

In [ ]:
import joblib
joblib.dump(model,"Netflix_model.pkl")

['Netflix_model.pkl']

In [ ]:
netflix_dataset.to_csv("Netflix_Dataset.csv")

In [ ]:
# =============================
# 5. RECOMMENDATION FUNCTION
# (Enhanced Visual Output)
# =============================

def recommend_movies(user_id):

    user_id = int(user_id)

    movies_copy = movie_title.copy()

    movies_copy['Predicted Rating'] = movies_copy['movie_id'].apply(
        lambda x: model.predict(user_id, x).est
    )

    top10 = movies_copy.sort_values(
        by="Predicted Rating",
        ascending=False
    ).head(10).reset_index(drop=True)


    # Create Netflix Style Cards
    cards = ""

    for i, row in top10.iterrows():

        rating_percent = (row['Predicted Rating'] / 5) * 100

        cards += f"""

        <div class="movie-card">

            <div class="rank">#{i+1}</div>

            <div class="movie-name">{row['name']}</div>

            <div class="rating-bar-bg">

                <div class="rating-bar-fill"
                     style="width:{rating_percent}%">

                     ⭐ {row['Predicted Rating']:.2f}

                </div>

            </div>

        </div>

        """

    return f"<div class='card-container'>{cards}</div>"



# =============================
# 6. ULTRA NETFLIX CSS
# =============================

css = """

/* ===== GLOBAL BACKGROUND ===== */

body {

    background-color: #000000 !important;

}


/* ===== MAIN CONTAINER ===== */

.gradio-container {

    background-color: #000000 !important;

}


/* ===== NETFLIX AI GLOWING HEADER ===== */

#title {

text-align:center;
font-size:60px;
font-weight:900;
color:#E50914;
margin-top:20px;
margin-bottom:10px;
letter-spacing:4px;

/* GLOW EFFECT */

text-shadow:

0 0 10px #E50914,
0 0 20px #E50914,
0 0 40px #E50914,
0 0 80px #E50914;

animation: glowPulse 2s infinite alternate;

}


/* Glow animation */

@keyframes glowPulse {

from {

text-shadow:
0 0 10px #E50914,
0 0 20px #E50914;

}

to {

text-shadow:
0 0 20px #ff1a1a,
0 0 40px #ff1a1a,
0 0 80px #ff1a1a;

}

}


/* ===== SUBTITLE ===== */

#subtitle {

text-align:center;
font-size:22px;
color:white;
margin-bottom:40px;

}


/* ===== DROPDOWN ===== */

.gr-dropdown {

background-color:#111111 !important;
color:white !important;
border:1px solid #E50914 !important;

}


/* ===== BUTTON ===== */

.gr-button {

background: linear-gradient(90deg, #E50914, #ff0000) !important;

color:white !important;

font-size:18px !important;

font-weight:bold;

border:none !important;

border-radius:10px !important;

padding:15px !important;

box-shadow:0 0 20px #E50914;

transition:0.3s;

}


.gr-button:hover {

transform: scale(1.08);

box-shadow:

0 0 20px #ff0000,
0 0 40px #ff0000,
0 0 60px #ff0000;

}


/* ===== CARD CONTAINER ===== */

.card-container {

display:flex;
flex-wrap:wrap;
justify-content:center;
gap:30px;

}


/* ===== MOVIE CARD WITH RED GLOW ===== */

.movie-card {

background: linear-gradient(145deg, #0d0d0d, #1a0000);

padding:25px;

border-radius:15px;

width:420px;

border:1px solid #E50914;

box-shadow:

0 0 10px #E50914,
0 0 20px #E50914;

transition:0.4s;

}


/* HOVER GLOW */

.movie-card:hover {

transform: scale(1.07);

box-shadow:

0 0 20px #ff0000,
0 0 40px #ff0000,
0 0 80px #ff0000;

}


/* ===== RANK ===== */

.rank {

color:#ff1a1a;

font-size:30px;

font-weight:bold;

margin-bottom:10px;

}


/* ===== MOVIE NAME ===== */

.movie-name {

color:white;

font-size:22px;

font-weight:600;

margin-bottom:15px;

}


/* ===== RATING BAR ===== */

.rating-bar-bg {

background:#330000;

border-radius:20px;

}


.rating-bar-fill {

background: linear-gradient(90deg, #ff0000, #E50914);

padding:10px;

border-radius:20px;

color:white;

font-weight:bold;

box-shadow:0 0 10px #ff0000;

}

"""



# =============================
# 7. BUILD NETFLIX PRO UI
# =============================

import gradio as gr

user_list = sorted(netflix_dataset['customer_id'].unique())


with gr.Blocks(css=css, theme=gr.themes.Soft()) as app:


    gr.HTML("<div id='title'>NETFLIX AI</div>")

    gr.HTML("<div id='subtitle'>Personalized Movie Recommendation Engine</div>")


    with gr.Row():

        user_dropdown = gr.Dropdown(

            choices=user_list,
            label=" Select User ID",
            value=user_list[0],
            interactive=True

        )


    recommend_btn = gr.Button(" Recommend Movies")


    output_cards = gr.HTML()



    def display(user):

        return recommend_movies(user)



    recommend_btn.click(

        fn=display,
        inputs=user_dropdown,
        outputs=output_cards

    )



# =============================
# 8. LAUNCH
# =============================

app.launch()

/tmp/ipython-input-2579402518.py:312: DeprecationWarning: The 'theme' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'theme' to Blocks.launch() instead.
  with gr.Blocks(css=css, theme=gr.themes.Soft()) as app:
/tmp/ipython-input-2579402518.py:312: DeprecationWarning: The 'css' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'css' to Blocks.launch() instead.
  with gr.Blocks(css=css, theme=gr.themes.Soft()) as app:

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://68e7c6b3fa1f6cd815.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)