In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
netflix_dataset=pd.read_csv('/content/drive/MyDrive/NETFLIX/Copy of combined_data_1.txt.zip',header=None,names=['customer_id','ratings'],usecols=[0,1])

In [3]:
netflix_dataset

         customer_id  ratings
0                 1:      NaN
1            1488844      3.0
2             822109      5.0
3             885013      4.0
4              30878      4.0
...              ...      ...
24058258     2591364      2.0
24058259     1791000      2.0
24058260      512536      5.0
24058261      988963      3.0
24058262     1704416      3.0

[24058263 rows x 2 columns]

# CUSTOMER ID COLUMN CONSIST OF BOTH MOVIE ID AND CUSTOMER ID,WHICH IS REPRESENTED AS NAN AT RATINGS COLUMN.

In [4]:
# NUMBER OF MOVIES:
movie_count=netflix_dataset.isnull().sum()
movie_count=movie_count['ratings']
movie_count

4499

In [5]:
# FINDING OF TOTAL NUMBER OF CUSTOMERS:-
total_customer=netflix_dataset['customer_id'].nunique() - movie_count

In [6]:
total_customer #TOTAL NUMBER OF CUSTOMERS

470758

In [7]:
# COUNT OF RATINGS:-
rating_count=netflix_dataset['ratings'].count() - movie_count

In [8]:
rating_count

24049265

In [9]:
given_ratings=netflix_dataset['ratings'].value_counts() #unique count of ratings

In [10]:
# NOW WE HAVE TO REMOVE THE NUMBER OF MOVIE ID FROM CUSTOMER ID COL,AND NEED TO SEPERATE THEM.
customer_ids=[]
for value in netflix_dataset['customer_id']:
  if ':' in value:
    id=value.replace(':','')
  customer_ids.append(id)

In [11]:
customer_ids

['1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 ...]

In [12]:
netflix_dataset['movie_id']=customer_ids #ADDING THE ARRAY WITH THE DATASET.

In [13]:
netflix_dataset

         customer_id  ratings movie_id
0                 1:      NaN        1
1            1488844      3.0        1
2             822109      5.0        1
3             885013      4.0        1
4              30878      4.0        1
...              ...      ...      ...
24058258     2591364      2.0     4499
24058259     1791000      2.0     4499
24058260      512536      5.0     4499
24058261      988963      3.0     4499
24058262     1704416      3.0     4499

[24058263 rows x 3 columns]

In [14]:
# now removing the cust_id from custimer_if column.
netflix_dataset.dropna(inplace=True)

In [15]:
netflix_dataset

         customer_id  ratings movie_id
1            1488844      3.0        1
2             822109      5.0        1
3             885013      4.0        1
4              30878      4.0        1
5             823519      3.0        1
...              ...      ...      ...
24058258     2591364      2.0     4499
24058259     1791000      2.0     4499
24058260      512536      5.0     4499
24058261      988963      3.0     4499
24058262     1704416      3.0     4499

[24053764 rows x 3 columns]

In [16]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   customer_id  object
 1   ratings      float64
 2   movie_id     object
dtypes: float64(1), object(2)
memory usage: 734.1+ MB

In [17]:
# CONVERTING THE CUSTOMER_ID INTO INT
netflix_dataset['customer_id']=netflix_dataset['customer_id'].astype(int)

In [18]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   customer_id  int64
 1   ratings      float64
 2   movie_id     object
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [19]:
movie_rate_count=netflix_dataset['movie_id'].value_counts()

In [20]:
movie_rate_count # these are the unique no. of ratings a movie got.

movie_id
1905    193941
2152    162597
3860    160454
4432    156183
571     154832
         ...
4294        44
915         43
3656        42
4338        39
4362        36
Name: count, Length: 4499, dtype: int64

In [21]:
# we need movies above 60% threshold.
threshold=round(movie_rate_count.quantile(0.6))
threshold

908

In [49]:
dropped_movies=movie_rate_count[movie_rate_count<threshold].index #these are the movies which are less than threshold review.
dropped_movies

Index(['1598', '1733', '1647', '4099', '1616', '1446', '263', '4259', '160',
       '1988',
       ...
       '1858', '4035', '3693', '2805', '820', '4294', '915', '3656', '4338',
       '4362'],
      dtype='object', name='movie_id', length=2699)

In [23]:
# if we find the number of customers then we can find that how many ratings each people has done.
customer_review_count=netflix_dataset['customer_id'].value_counts()
customer_review_count

customer_id
305344     4467
387418     4422
2439493    4195
1664010    4019
2118461    3769
           ...
1300341       1
2550360       1
11848         1
930788        1
594210        1
Name: count, Length: 470758, dtype: int64

In [24]:
# Benchmark for the customer reviw:-
bench_mark=customer_review_count.quantile(0.6)
bench_mark

36.0

In [25]:
# dropped customers:
dropped_customer=customer_review_count[customer_review_count < bench_mark].index
dropped_customer

Index([2194851,  600295, 1739398, 1157368,  532108, 2157249,  256134,  640441,
       1272324, 1346990,
       ...
       1969065,  899932,  611596, 2147176,  811650, 1300341, 2550360,   11848,
        930788,  594210],
      dtype='int64', name='customer_id', length=282042)

In [26]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   customer_id  int64
 1   ratings      float64
 2   movie_id     object
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [27]:
# now we need these customers and movies which are not in dropped.using isin() method we will perform.
netflix_dataset=netflix_dataset[~netflix_dataset['customer_id'].isin(dropped_customer)]
netflix_dataset=netflix_dataset[~netflix_dataset['movie_id'].isin(dropped_movies)]

In [28]:
netflix_dataset

          customer_id  ratings movie_id
696            712664      5.0        3
697           1331154      4.0        3
698           2632461      3.0        3
699             44937      5.0        3
700            656399      4.0        3
...               ...      ...      ...
24056842      1055714      5.0     4496
24056843      2643029      4.0     4496
24056844       267802      4.0     4496
24056845      1559566      3.0     4496
24056846       293198      3.0     4496

[19695836 rows x 3 columns]

#**MODEL BUILDING PART:-**

In [29]:
#LOAD THE SECOND DATASET:-
df_title=pd.read_csv('/content/drive/MyDrive/NETFLIX/Copy of movie_titles.csv',encoding='ISO-8859-1',header=None,names=['movie_id','year','name'],usecols=[0,1,2])

In [30]:
df_title

       movie_id    year                                               name
0             1  2003.0                                    Dinosaur Planet
1             2  2004.0                         Isle of Man TT 2004 Review
2             3  1997.0                                          Character
3             4  1994.0                       Paula Abdul's Get Up & Dance
4             5  2004.0                           The Rise and Fall of ECW
...         ...     ...                                                ...
17764     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765     17767  2004.0                  Fidel Castro: American Experience
17766     17768  2000.0                                              Epoch
17767     17769  2003.0                                        The Company
17768     17770  2003.0                                       Alien Hunter

[17769 rows x 3 columns]

In [31]:
#!pip install numpy==1.23.5

In [32]:
# svd is the process of dividing matrix into smaller part
!pip install scikit-surprise  # this is the library where svd present

Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.11/dist-packages (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-surprise) (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-surprise) (1.23.5)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-surprise) (1.15.3)

In [33]:
#importing libraries:
from surprise import SVD,Reader,Dataset #svd:-singular value decomposition.
from surprise.model_selection import cross_validate

In [34]:
reader=Reader() #its for reading the objects

In [60]:
data=Dataset.load_from_df(netflix_dataset[['movie_id','customer_id','ratings']][:1000000],reader)

In [61]:
data #data is stored into the object

In [62]:
model=SVD()

In [63]:
#cross validation technique using rmse(root mean square error)
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([0.96787246, 0.96678054, 0.96448822]),
 'fit_time': (14.546041488647461, 14.838376998901367, 15.54439640045166),
 'test_time': (4.3296167850494385, 3.7892377376556396, 3.3646841049194336)}

In [39]:
user_rating=netflix_dataset[netflix_dataset['customer_id']==1331154]

In [40]:
user_rating

          customer_id  ratings movie_id
697           1331154      4.0        3
5178          1331154      4.0        8
31460         1331154      3.0       18
92840         1331154      4.0       30
224761        1331154      3.0       44
...               ...      ...      ...
23439584      1331154      4.0     4389
23546489      1331154      2.0     4402
23649431      1331154      4.0     4432
23844441      1331154      3.0     4472
23985561      1331154      4.0     4488

[253 rows x 3 columns]

In [41]:
movie_title=df_title.copy() #total movies

In [42]:
movie_title

       movie_id    year                                               name
0             1  2003.0                                    Dinosaur Planet
1             2  2004.0                         Isle of Man TT 2004 Review
2             3  1997.0                                          Character
3             4  1994.0                       Paula Abdul's Get Up & Dance
4             5  2004.0                           The Rise and Fall of ECW
...         ...     ...                                                ...
17764     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765     17767  2004.0                  Fidel Castro: American Experience
17766     17768  2000.0                                              Epoch
17767     17769  2003.0                                        The Company
17768     17770  2003.0                                       Alien Hunter

[17769 rows x 3 columns]

In [55]:
# i want to eliminate dropped_movies columns from the movie title column

# Now, eliminate the movies present in 'dropped_movies' from 'movie_title' DataFrame
movie_title = movie_title[~movie_title['movie_id'].astype(str).isin(dropped_movies.astype(str))]
movie_title

       movie_id    year                                               name
2             3  1997.0                                          Character
4             5  2004.0                           The Rise and Fall of ECW
5             6  1997.0                                               Sick
7             8  2004.0                         What the #$*! Do We Know!?
15           16  1996.0                                          Screamers
...         ...     ...                                                ...
17764     17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765     17767  2004.0                  Fidel Castro: American Experience
17766     17768  2000.0                                              Epoch
17767     17769  2003.0                                        The Company
17768     17770  2003.0                                       Alien Hunter

[15070 rows x 3 columns]

In [56]:
movie_title['Estimated']=movie_title['movie_id'].apply(lambda x: model.predict(1331154,x).est)

<ipython-input-56-2318960625>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_title['Estimated']=movie_title['movie_id'].apply(lambda x: model.predict(1331154,x).est)

In [59]:
#using for loop we can do this also
#est=[]
#for i in movie_title['movie_id']:
 # est.append(model.predict(1331154,i).est)
#movie_title['Estimated']=est

In [58]:
movie_title.sort_values(by='Estimated',ascending=False).head(10) # this the prediction the customer can rate these movies

       movie_id    year                                   name  Estimated
13873     13875  1982.0       Gilbert and Sullivan: The Mikado   3.885814
17449     17451  2000.0                     Along for the Ride   3.864336
6459       6460  2005.0     The Game: The Documentary: The DVD   3.854730
3997       3998  1988.0  Joseph Campbell and The Power of Myth   3.806814
13509     13511  1993.0                 Much Ado About Nothing   3.800480
5726       5727  1984.0                   The Last Starfighter   3.781839
17508     17510  2004.0                          Stella Street   3.735042
4752       4753  2003.0                            Cabin Fever   3.733416
11308     11310  1954.0                             Varietease   3.725108
10372     10374  1997.0                Goosebumps: Scary House   3.722936

## This is how by changing the custimer id we can predict the rating the customer can provide for all the movies and based on this movies can be suggested.